### ISSUE TITLE
The blog is empty.

### ISSUE THREAD

**Issue by ghost** [GardenCityRuby/GCRC2014#5]
http://www.gardencityruby.org/blog.html

Is Prakash's post deployed?

I see it here: http://gardencityruby.github.io/GCRC2014/blog.html

**Comment by emilsoman** [comment]
Not yet . The blog is currently in the master branch . @gnufied is working
on the continuous deployment. It will be up when that's done.

**Comment by prakashmurthy** [comment]
Why not continue to deploy manually - to the current cloud account - till the continuous deployment is ready on a different cloud account?

**Comment by emilsoman** [comment]
@prakashmurthy  I've done a manual deployment just now. Your post should be live at http://www.gardencityruby.org/volunteer-for-handling-wifi-&-internet-connectivity/

**Comment by prakashmurthy** [comment]
Thanks @emilsoman. Please continue to manually deploy regularly ( 5 or 6 times a day) till the automatic deploy functionality in place. 

@All: Please start making modifications to the site by changing the code on the master branch. Emil will deploy the code from the 'deploy' branch later on. Make the changes very small & self contained (one commit, with very clear commit message about the change made) so that it is not just easy to deploy, but also easy to reject/revert the change if required. 

I will add minor texts related to the various parts of the website later today/this weekend.

**Comment by gnufied** [comment]
Can you point www.gardencityruby.org (with www and without www)
to 188.40.122.145 ? The auto deployment job has been setup and it is
working well now.

Any changes to master are automatically detected and deployed.

**Comment by prakashmurthy** [comment]
Thanks Hemant. Did anybody make any changes to the website to verify?

**Comment by gnufied** [comment]
I can't verify the IP from outside because IP has other stuff as well.

But if DNS change is made then virtual host entry will kick in and it will
work.

**Comment by prakashmurthy** [comment]
I added the [about page content](https://github.com/GardenCityRuby/GCRC2014/commit/e56b9686289ec79c07eb65d31f6290a2010aabf1). How long before it shows up on the website?

**Comment by emilsoman** [comment]
@gnufied , thanks ! Let me work on the DNS

**Comment by gnufied** [comment]
the change is immediate, but nobody has made the DNS switch. It is still
point to old IP Address.

Someone who has access to DNS needs to point it to the address I gave.
